=== loco-philippe/IRVE/OCPI/source/schema.json
{
    "$id": "https://www.jsonschemavalidator.net/s/9jXn0qs6",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Qualicharge_OCPI_Tariff",
    "description": "This schema defines the structure and validation rules for OCPI Tariff objects used in the Qualicharge platform. It includes properties of OCPI 2.2 and OCPI 2.3 and requires only the properties that are applicable to the Qualicharge platform. The schema ensures that OCPI Tariff data adheres to the required format and constraints.",
    "type": "object",
    "required": [
        "id",
        "elements",
        "last_updated"
    ],
    "properties": {
        "country_code": {
            "type": "string",
            "minLength": 2,
            "maxLength": 2,
            "description": "ISO-3166 alpha-2 country code"
        },
        "party_id": {
            "type": "string",
            "minLength": 3,
            "maxLength": 3,
            "description": "CPO ID"
        },
        "id": {
            "type": "string",
            "maxLength": 36,
            "description": "Unique tariff ID"
        },
        "currency": {
            "type": "string",
            "minLength": 3,
            "maxLength": 3,
            "description": "ISO-4217 currency code (ex: EUR)"
        },
        "tariff_alt_text": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "language": {
                        "type": "string"
                    },
                    "text": {
                        "type": "string"
                    }
                }
            }
        },
        "start_date_time": {
            "type": "string",
            "format": "date-time"
        },
        "end_date_time": {
            "type": "string",
            "format": "date-time"
        },
        "last_updated": {
            "type": "string",
            "format": "date-time"
        },
        "tax_included": {
            "enum": [
                "YES",
                "NO",
                "N/A"
            ]
        },
        "min_price": {
            "anyOf": [
                {
                    "description": "OCPI 2.2 format",
                    "type": "object",
                    "required": [
                        "excl_vat"
                    ],
                    "properties": {
                        "excl_vat": {
                            "type": "number"
                        },
                        "incl_vat": {
                            "type": "number"
                        }
                    }
                },
                {
                    "description": "OCPI 2.3 format",
                    "type": "object",
                    "required": [
                        "before_taxes"
                    ],
                    "properties": {
                        "before_taxes": {
                            "type": "number"
                        },
                        "after_taxes": {
                            "type": "number"
                        }
                    }
                }
            ]
        },
        "max_price": {
            "anyOf": [
                {
                    "description": "OCPI 2.2 format",
                    "type": "object",
                    "required": [
                        "excl_vat"
                    ],
                    "properties": {
                        "excl_vat": {
                            "type": "number"
                        },
                        "incl_vat": {
                            "type": "number"
                        }
                    }
                },
                {
                    "description": "OCPI 2.3 format",
                    "type": "object",
                    "required": [
                        "before_taxes"
                    ],
                    "properties": {
                        "before_taxes": {
                            "type": "number"
                        },
                        "after_taxes": {
                            "type": "number"
                        }
                    }
                }
            ]
        },
        "elements": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "required": [
                    "price_components"
                ],
                "properties": {
                    "price_components": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": [
                                "type",
                                "price"
                            ],
                            "properties": {
                                "type": {
                                    "description": "additional type for congestion pricing",
                                    "enum": [
                                        "ENERGY",
                                        "FLAT",
                                        "PARKING_TIME",
                                        "TIME",
                                        "CONGESTION_TIME"
                                    ]
                                },
                                "price": {
                                    "type": "number"
                                },
                                "vat": {
                                    "type": "number"
                                },
                                "step_size": {
                                    "type": "integer",
                                    "minimum": 1
                                }
                            }
                        }
                    },
                    "restrictions": {
                        "type": "object",
                        "properties": {
                            "start_time": {
                                "type": "string",
                                "pattern": "^([01]\\d|2[0-3]):([0-5]\\d)$"
                            },
                            "end_time": {
                                "type": "string",
                                "pattern": "^([01]\\d|2[0-3]):([0-5]\\d)$"
                            },
                            "start_date": {
                                "type": "string",
                                "format": "date"
                            },
                            "end_date": {
                                "type": "string",
                                "format": "date"
                            },
                            "min_kwh": {
                                "type": "number"
                            },
                            "max_kwh": {
                                "type": "number"
                            },
                            "min_current": {
                                "type": "number"
                            },
                            "max_current": {
                                "type": "number"
                            },
                            "min_power": {
                                "type": "number"
                            },
                            "max_power": {
                                "type": "number"
                            },
                            "min_duration": {
                                "type": "integer"
                            },
                            "max_duration": {
                                "type": "integer"
                            },
                            "day_of_week": {
                                "type": "array",
                                "items": {
                                    "enum": [
                                        "MONDAY",
                                        "TUESDAY",
                                        "WEDNESDAY",
                                        "THURSDAY",
                                        "FRIDAY",
                                        "SATURDAY",
                                        "SUNDAY"
                                    ]
                                }
                            },
                            "reservation": {
                                "enum": [
                                    "RESERVATION",
                                    "RESERVATION_EXPIRES"
                                ]
                            },
                            "min_vehicle_soc": {
                                "description": "additional type for congestion pricing",
                                "type": "integer"
                            },
                            "min_congestion_threshold": {
                                "description": "additional type for congestion pricing",
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        }
    }
}

=== loco-philippe/IRVE/OCPI/data/izivia/jsons/IZIVIA-IMPACT-LF-gt-50.json
{
  "country_code": "FR",
  "party_id": "ILF",
  "id": "IZIVIA-IMPACT-LF-GT-50",
  "currency": "EUR",
  "tariff_alt_text": [
    {
      "language": "fr",
      "text": "0.52€/kWh + 2€/5min si branchement sans charge. Toute énergie au kWh et tranche de 5min entamée est due."
    }
  ],
  "elements": [
    {
      "price_components": [
        { "type": "ENERGY", "price": 0.4333, "vat": 20.0, "step_size": 1000 },
        { "type": "PARKING_TIME", "price": 19.98996, "vat": 20.0, "step_size": 300 }
      ]
    }
  ],
  "last_updated": "2026-06-18T00:00:00Z"
}

=== loco-philippe/IRVE/OCPI/data/izivia/jsons/IZP-MLH-150.json
{
  "country_code": "FR",
  "party_id": "IIM",
  "id": "IZP-MLH-150",
  "currency": "EUR",
  "tariff_alt_text": [
    {
      "language": "fr",
      "text": "0.55€/kWh puis 2€/5min post-charge. Tous kWh ou minute entamés sont dus."
    }
  ],
  "elements": [
    {
      "price_components": [
        { "type": "ENERGY", "price": 0.4583, "vat": 20.0, "step_size": 1000 },
        { "type": "PARKING_TIME", "price": 20.0, "vat": 20.0, "step_size": 300 }
      ]
    }
  ],
  "last_updated": "2026-06-18T00:00:00Z"
}

=== loco-philippe/IRVE/OCPI/data/izivia/jsons/LYON-my50kW.json
{
  "country_code": "FR",
  "party_id": "GLY",
  "id": "LYON-my50kW",
  "currency": "EUR",
  "tariff_alt_text": [
    {
      "language": "fr",
      "text": "0,45€ par kWh + supplément de 0,20€ par minute après 45 minutes de connexion"
    }
  ],
  "elements": [
    {
      "price_components": [
        { "type": "ENERGY", "price": 0.375, "vat": 20.0, "step_size": 1000 }
      ]
    },
    {
      "price_components": [
        { "type": "TIME", "price": 0, "vat": 20.0, "step_size": 60 }
      ],
      "restrictions": { "max_duration": 2700 }
    },
    {
      "price_components": [
        { "type": "TIME", "price": 10.002, "vat": 20.0, "step_size": 60 }
      ],
      "restrictions": { "min_duration": 2700 }
    }
  ],
  "last_updated": "2026-06-18T00:00:00Z"
}

=== loco-philippe/IRVE/OCPI/data/izivia/jsons/SIGE-24KW.json
{
  "country_code": "FR",
  "party_id": "SIG",
  "id": "SIGE-24KW",
  "currency": "EUR",
  "tariff_alt_text": [
    {
      "language": "fr",
      "text": "Borne rapide 24kW : 0,45€/kWh + 0€/min pendant 2h puis 0,2€/min. Toute énergie ou minute entamée est due."
    }
  ],
  "elements": [
    {
      "price_components": [
        { "type": "ENERGY", "price": 0.375, "vat": 20.0, "step_size": 1000 }
      ]
    },
    {
      "price_components": [
        { "type": "TIME", "price": 0, "vat": 20.0, "step_size": 60 }
      ],
      "restrictions": { "max_duration": 7200 }
    },
    {
      "price_components": [
        { "type": "TIME", "price": 9.999, "vat": 20.0, "step_size": 60 }
      ],
      "restrictions": { "min_duration": 7200 }
    }
  ],
  "last_updated": "2026-06-18T00:00:00Z"
}

=== loco-philippe/IRVE/OCPI/data/izivia/jsons/OAZS-izivia-express-50kW.json
{
  "country_code": "FR",
  "party_id": "E04",
  "id": "OAZS-izivia-express-50kW",
  "currency": "EUR",
  "tariff_alt_text": [
    {
      "language": "fr",
      "text": "0.45€/kWh + 1€/5min post-charge. Toute durée ou énergie entamée est due."
    }
  ],
  "elements": [
    {
      "price_components": [
        { "type": "ENERGY", "price": 0.375, "vat": 20.0, "step_size": 1000 },
        { "type": "PARKING_TIME", "price": 10.0, "vat": 20.0, "step_size": 300 }
      ]
    }
  ],
  "last_updated": "2026-06-18T00:00:00Z"
}

=== loco-philippe/IRVE/OCPI/data/izivia/jsons/IZIVIA-MAX-50-100.json
{
  "country_code": "FR",
  "party_id": "IMX",
  "id": "IZIVIA-MAX-50-100",
  "currency": "EUR",
  "tariff_alt_text": [
    {
      "language": "fr",
      "text": "0.45€/kWh + 0.4€/min si branchement sans charge. Toute énergie au kWh et minute entamée est due"
    }
  ],
  "elements": [
    {
      "price_components": [
        { "type": "ENERGY", "price": 0.38, "vat": 20.0, "step_size": 1000 },
        { "type": "PARKING_TIME", "price": 20.01, "vat": 20.0, "step_size": 60 }
      ]
    }
  ],
  "last_updated": "2026-06-18T00:00:00Z"
}

=== loco-philippe/IRVE/OCPI/data/izivia/jsons/IZIVIA-24KW-LIMOGES.json
{
  "country_code": "FR",
  "party_id": "IXL",
  "id": "IZIVIA-24KW-LIMOGES",
  "currency": "EUR",
  "tariff_alt_text": [
    {
      "language": "fr",
      "text": "Entre 8h et 20h: 0.42€/kWh puis 4€/h post-charge. Tous kWh ou minute entamés sont dus.  Entre 20h et 8h: forfait de connexion de 5€ et à partir de 20kWh, supplément de 0.3€/kWh."
    }
  ],
  "elements": [
    {
      "price_components": [
        { "type": "FLAT", "price": 4.1667, "vat": 20.0, "step_size": 1 }
      ],
      "restrictions": { "start_time": "20:00", "end_time": "08:00" }
    },
    {
      "price_components": [
        { "type": "ENERGY", "price": 0.25, "vat": 20.0, "step_size": 1000 }
      ],
      "restrictions": { "start_time": "20:00", "end_time": "08:00", "min_kwh": 20 }
    },
    {
      "price_components": [
        { "type": "ENERGY", "price": 0.35, "vat": 20.0, "step_size": 1000 }
      ],
      "restrictions": { "start_time": "08:00", "end_time": "20:00" }
    },
    {
      "price_components": [
        { "type": "PARKING_TIME", "price": 3.333, "vat": 20.0, "step_size": 60 }
      ],
      "restrictions": { "start_time": "08:00", "end_time": "20:00" }
    }
  ],
  "last_updated": "2026-06-18T00:00:00Z"
}

=== loco-philippe/IRVE/OCPI/data/izivia/jsons/IZIVIA-FAST.json
{
  "country_code": "FR",
  "party_id": "IZF",
  "id": "IZIVIAFAST-MCDO-AM",
  "currency": "EUR",
  "tariff_alt_text": [
    {
      "language": "fr",
      "text": "0,30€/kWh (9h-11h, 15h-17h) ou 0,35€/kWh (hors créneaux). L'horaire de branchement définit le prix du kWh pour toute la session. Frais de stationnement après 1h : 0,30€/min. Tout kWh ou minute entamée est due."
    }
  ],
  "elements": [
    {
      "price_components": [
        {
          "type": "ENERGY",
          "price": 0.25,
          "vat": 20.0,
          "step_size": 1000
        }
      ],
      "restrictions": {
        "start_time": "09:00",
        "end_time": "11:00"
      }
    },
    {
      "price_components": [
        {
          "type": "ENERGY",
          "price": 0.25,
          "vat": 20.0,
          "step_size": 1000
        }
      ],
      "restrictions": {
        "start_time": "15:00",
        "end_time": "17:00"
      }
    },
    {
      "price_components": [
        {
          "type": "ENERGY",
          "price": 0.2917,
          "vat": 20.0,
          "step_size": 1000
        }
      ],
      "restrictions": {
        "start_time": "00:00",
        "end_time": "09:00"
      }
    },
    {
      "price_components": [
        {
          "type": "ENERGY",
          "price": 0.2917,
          "vat": 20.0,
          "step_size": 1000
        }
      ],
      "restrictions": {
        "start_time": "11:00",
        "end_time": "15:00"
      }
    },
    {
      "price_components": [
        {
          "type": "ENERGY",
          "price": 0.2917,
          "vat": 20.0,
          "step_size": 1000
        }
      ],
      "restrictions": {
        "start_time": "17:00",
        "end_time": "23:59"
      }
    },
    {
      "price_components": [
        {
          "type": "TIME",
          "price": 0.0,
          "vat": 20.0,
          "step_size": 60
        }
      ],
      "restrictions": {
        "min_duration": 0,
        "max_duration": 3600
      }
    },
    {
      "price_components": [
        {
          "type": "TIME",
          "price": 15.0,
          "vat": 20.0,
          "step_size": 60
        }
      ],
      "restrictions": {
        "min_duration": 3600
      }
    }
  ],
  "last_updated": "2026-06-18T12:00:00Z"
}
