=== loco-philippe/IRVE/OCPI/source/schema.json
{
    "$id": "https://www.jsonschemavalidator.net/s/9jXn0qs6",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Qualicharge_OCPI_Tariff",
    "description": "This schema defines the structure and validation rules for OCPI Tariff objects used in the Qualicharge platform. It includes properties of OCPI 2.2 and OCPI 2.3 and requires only the properties that are applicable to the Qualicharge platform. The schema ensures that OCPI Tariff data adheres to the required format and constraints.",
    "type": "object",
    "required": [
        "id",
        "elements",
        "last_updated"
    ],
    "properties": {
        "country_code": {
            "type": "string",
            "minLength": 2,
            "maxLength": 2,
            "description": "ISO-3166 alpha-2 country code"
        },
        "party_id": {
            "type": "string",
            "minLength": 3,
            "maxLength": 3,
            "description": "CPO ID"
        },
        "id": {
            "type": "string",
            "maxLength": 36,
            "description": "Unique tariff ID"
        },
        "currency": {
            "type": "string",
            "minLength": 3,
            "maxLength": 3,
            "description": "ISO-4217 currency code (ex: EUR)"
        },
        "tariff_alt_text": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "language": {
                        "type": "string"
                    },
                    "text": {
                        "type": "string"
                    }
                }
            }
        },
        "start_date_time": {
            "type": "string",
            "format": "date-time"
        },
        "end_date_time": {
            "type": "string",
            "format": "date-time"
        },
        "last_updated": {
            "type": "string",
            "format": "date-time"
        },
        "tax_included": {
            "enum": [
                "YES",
                "NO",
                "N/A"
            ]
        },
        "min_price": {
            "anyOf": [
                {
                    "description": "OCPI 2.2 format",
                    "type": "object",
                    "required": [
                        "excl_vat"
                    ],
                    "properties": {
                        "excl_vat": {
                            "type": "number"
                        },
                        "incl_vat": {
                            "type": "number"
                        }
                    }
                },
                {
                    "description": "OCPI 2.3 format",
                    "type": "object",
                    "required": [
                        "before_taxes"
                    ],
                    "properties": {
                        "before_taxes": {
                            "type": "number"
                        },
                        "after_taxes": {
                            "type": "number"
                        }
                    }
                }
            ]
        },
        "max_price": {
            "anyOf": [
                {
                    "description": "OCPI 2.2 format",
                    "type": "object",
                    "required": [
                        "excl_vat"
                    ],
                    "properties": {
                        "excl_vat": {
                            "type": "number"
                        },
                        "incl_vat": {
                            "type": "number"
                        }
                    }
                },
                {
                    "description": "OCPI 2.3 format",
                    "type": "object",
                    "required": [
                        "before_taxes"
                    ],
                    "properties": {
                        "before_taxes": {
                            "type": "number"
                        },
                        "after_taxes": {
                            "type": "number"
                        }
                    }
                }
            ]
        },
        "elements": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "required": [
                    "price_components"
                ],
                "properties": {
                    "price_components": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": [
                                "type",
                                "price"
                            ],
                            "properties": {
                                "type": {
                                    "description": "additional type for congestion pricing",
                                    "enum": [
                                        "ENERGY",
                                        "FLAT",
                                        "PARKING_TIME",
                                        "TIME",
                                        "CONGESTION_TIME"
                                    ]
                                },
                                "price": {
                                    "type": "number"
                                },
                                "vat": {
                                    "type": "number"
                                },
                                "step_size": {
                                    "type": "integer",
                                    "minimum": 1
                                }
                            }
                        }
                    },
                    "restrictions": {
                        "type": "object",
                        "properties": {
                            "start_time": {
                                "type": "string",
                                "pattern": "^([01]\\d|2[0-3]):([0-5]\\d)$"
                            },
                            "end_time": {
                                "type": "string",
                                "pattern": "^([01]\\d|2[0-3]):([0-5]\\d)$"
                            },
                            "start_date": {
                                "type": "string",
                                "format": "date"
                            },
                            "end_date": {
                                "type": "string",
                                "format": "date"
                            },
                            "min_kwh": {
                                "type": "number"
                            },
                            "max_kwh": {
                                "type": "number"
                            },
                            "min_current": {
                                "type": "number"
                            },
                            "max_current": {
                                "type": "number"
                            },
                            "min_power": {
                                "type": "number"
                            },
                            "max_power": {
                                "type": "number"
                            },
                            "min_duration": {
                                "type": "integer"
                            },
                            "max_duration": {
                                "type": "integer"
                            },
                            "day_of_week": {
                                "type": "array",
                                "items": {
                                    "enum": [
                                        "MONDAY",
                                        "TUESDAY",
                                        "WEDNESDAY",
                                        "THURSDAY",
                                        "FRIDAY",
                                        "SATURDAY",
                                        "SUNDAY"
                                    ]
                                }
                            },
                            "reservation": {
                                "enum": [
                                    "RESERVATION",
                                    "RESERVATION_EXPIRES"
                                ]
                            },
                            "min_vehicle_soc": {
                                "description": "additional type for congestion pricing",
                                "type": "integer"
                            },
                            "min_congestion_threshold": {
                                "description": "additional type for congestion pricing",
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        }
    }
}

=== loco-philippe/IRVE/OCPI/data/izivia/jsons/LYON-my24kW.json
{
  "country_code": "FR",
  "party_id": "GLY",
  "id": "LYON-my24kW",
  "currency": "EUR",
  "tariff_alt_text": [
    {
      "language": "fr",
      "text": "Entre 8h et 20h : 6€ par heure. Facturation par minute effectivement branchée. Entre 20h et 8h : forfait de connexion de 6€ et, à partir de 20kWh, supplément de 0,38€ par kWh."
    }
  ],
  "elements": [
    {
      "price_components": [
        { "type": "FLAT", "price": 5.0, "vat": 20.0, "step_size": 1 }
      ],
      "restrictions": { "start_time": "20:00", "end_time": "08:00" }
    },
    {
      "price_components": [
        { "type": "ENERGY", "price": 0.3167, "vat": 20.0, "step_size": 1000 }
      ],
      "restrictions": { "start_time": "20:00", "end_time": "08:00", "min_kwh": 20 }
    },
    {
      "price_components": [
        { "type": "TIME", "price": 4.998, "vat": 20.0, "step_size": 60 }
      ],
      "restrictions": { "start_time": "08:00", "end_time": "20:00" }
    }
  ],
  "last_updated": "2026-06-18T00:00:00Z"
}

=== loco-philippe/IRVE/OCPI/data/izivia/jsons/IZIVIA-GF-50-100-0.54.json
{
  "country_code": "FR",
  "party_id": "IGF",
  "id": "IZIVIA-GF-50-100-0.54",
  "currency": "EUR",
  "tariff_alt_text": [
    {
      "language": "fr",
      "text": "0.54€/kWh + 2€/5min si branchement sans charge. Toute énergie au kWh et tranche de 5 minutes entamée est due."
    }
  ],
  "elements": [
    {
      "price_components": [
        { "type": "ENERGY", "price": 0.45, "vat": 20.0, "step_size": 1000 },
        { "type": "PARKING_TIME", "price": 20.0, "vat": 20.0, "step_size": 300 }
      ]
    }
  ],
  "last_updated": "2026-06-18T00:00:00Z"
}

=== loco-philippe/IRVE/OCPI/data/BP/bp_tariff.json
{
    "id": "BP_tariff_ad_hoc",
    "country_code": "FR",
    "party_id": "BPE",
    "elements": [
        {
            "price_components": [
                {
                    "type": "ENERGY",
                    "price": 0.49167,
                    "step_size": 1
                }
            ],
            "restrictions": {
                "min_power": 150
            }
        },
        {
            "price_components": [
                {
                    "type": "ENERGY",
                    "price": 0.38333,
                    "step_size": 1
                }
            ],
            "restrictions": {
                "min_power": 45,
                "max_power": 149
            }
        },
        {
            "price_components": [
                {
                    "type": "ENERGY",
                    "price": 0.35833,
                    "step_size": 1
                }
            ],
            "restrictions": {
                "max_power": 44
            }
        }
    ],
    "last_updated": "2024-06-25T10:26:26Z"
}

=== loco-philippe/IRVE/OCPI/data/izivia/jsons/IZP-MLH-24.json
{
  "country_code": "FR",
  "party_id": "IIM",
  "id": "IZP-MLH-24",
  "currency": "EUR",
  "tariff_alt_text": [
    {
      "language": "fr",
      "text": "Entre 8h et 20h: 0.42€/kWh puis 4€/h post-charge. Entre 20h et 8h: forfait de connexion de 6€ et à partir de 20kWh, supplément de 0.4€/kWh. Tous kWh ou minute entamés sont dus."
    }
  ],
  "elements": [
    {
      "price_components": [
        { "type": "FLAT", "price": 5.0, "vat": 20.0, "step_size": 1 }
      ],
      "restrictions": { "start_time": "20:00", "end_time": "08:00" }
    },
    {
      "price_components": [
        { "type": "ENERGY", "price": 0.3333, "vat": 20.0, "step_size": 1000 }
      ],
      "restrictions": { "start_time": "20:00", "end_time": "08:00", "min_kwh": 20 }
    },
    {
      "price_components": [
        { "type": "ENERGY", "price": 0.35, "vat": 20.0, "step_size": 1000 }
      ],
      "restrictions": { "start_time": "08:00", "end_time": "20:00" }
    },
    {
      "price_components": [
        { "type": "PARKING_TIME", "price": 3.333, "vat": 20.0, "step_size": 60 }
      ],
      "restrictions": { "start_time": "08:00", "end_time": "20:00" }
    }
  ],
  "last_updated": "2026-06-18T00:00:00Z"
}

=== loco-philippe/IRVE/OCPI/data/evzen/tariffs.json
[
    {
        "id": "303a999db1e8436d891395637110fbb2",
        "currency": "EUR",
        "elements": [
            {
                "price_components": [
                    {
                        "type": "ENERGY",
                        "price": 0.325,
                        "step_size": 1
                    }
                ],
                "restrictions": {
                    "start_date": "2025-11-19",
                    "end_date": "2026-01-23"
                }
            },
            {
                "price_components": [
                    {
                        "type": "ENERGY",
                        "price": 0.325,
                        "step_size": 1
                    }
                ],
                "restrictions": {
                    "start_date": "2026-01-23"
                }
            },
            {
                "price_components": [
                    {
                        "type": "ENERGY",
                        "price": 0.325,
                        "step_size": 1
                    }
                ],
                "restrictions": {
                    "start_date": "2024-01-01",
                    "end_date": "2025-01-01"
                }
            },
            {
                "price_components": [
                    {
                        "type": "ENERGY",
                        "price": 0.325,
                        "step_size": 1
                    }
                ],
                "restrictions": {
                    "start_date": "2025-01-01",
                    "end_date": "2025-11-19"
                }
            }
        ],
        "last_updated": "2026-02-12T02:20:04Z"
    },
    {
        "id": "9390bdd487804336807aaf69768e03df",
        "currency": "EUR",
        "elements": [
            {
                "price_components": [
                    {
                        "type": "ENERGY",
                        "price": 0.325,
                        "step_size": 1
                    }
                ],
                "restrictions": {
                    "start_date": "2025-11-19",
                    "end_date": "2026-01-23"
                }
            },
            {
                "price_components": [
                    {
                        "type": "ENERGY",
                        "price": 0.325,
                        "step_size": 1
                    }
                ],
                "restrictions": {
                    "start_date": "2026-01-23"
                }
            },
            {
                "price_components": [
                    {
                        "type": "ENERGY",
                        "price": 0.325,
                        "step_size": 1
                    }
                ],
                "restrictions": {
                    "start_date": "2024-01-01",
                    "end_date": "2025-01-01"
                }
            },
            {
                "price_components": [
                    {
                        "type": "ENERGY",
                        "price": 0.325,
                        "step_size": 1
                    }
                ],
                "restrictions": {
                    "start_date": "2025-01-01",
                    "end_date": "2025-11-19"
                }
            }
        ],
        "last_updated": "2026-02-12T02:20:04Z"
    },
    {
        "id": "b5dafd86e84b4243b906ead05482058a",
        "currency": "EUR",
        "elements": [
            {
                "price_components": [
                    {
                        "type": "ENERGY",
                        "price": 0.4583,
                        "step_size": 1
                    }
                ],
                "restrictions": {
                    "start_date": "2025-11-19",
                    "end_date": "2026-01-23"
                }
            },
            {
                "price_components": [
                    {
                        "type": "ENERGY",
                        "price": 0.4583,
                        "step_size": 1
                    }
                ],
                "restrictions": {
                    "start_date": "2026-01-23"
                }
            },
            {
                "price_components": [
                    {
                        "type": "ENERGY",
                        "price": 0.4583,
                        "step_size": 1
                    }
                ],
                "restrictions": {
                    "start_date": "2023-12-04",
                    "end_date": "2025-01-01"
                }
            },
            {
                "price_components": [
                    {
                        "type": "ENERGY",
                        "price": 0.4583,
                        "step_size": 1
                    }
                ],
                "restrictions": {
                    "start_date": "2025-01-01",
                    "end_date": "2025-11-19"
                }
            }
        ],
        "last_updated": "2026-02-12T02:20:04Z"
    },
    {
        "id": "d369901a61db4255a5fd40e4795b29e7",
        "currency": "EUR",
        "elements": [
            {
                "price_components": [
                    {
                        "type": "ENERGY",
                        "price": 0.4083,
                        "step_size": 1
                    }
                ],
                "restrictions": {
                    "start_date": "2025-11-19",
                    "end_date": "2026-01-23"
                }
            },
            {
                "price_components": [
                    {
                        "type": "ENERGY",
                        "price": 0.4083,
                        "step_size": 1
                    }
                ],
                "restrictions": {
                    "start_date": "2026-01-23"
                }
            },
            {
                "price_components": [
                    {
                        "type": "ENERGY",
                        "price": 0.4083,
                        "step_size": 1
                    }
                ],
                "restrictions": {
                    "start_date": "2024-01-01",
                    "end_date": "2025-01-01"
                }
            },
            {
                "price_components": [
                    {
                        "type": "ENERGY",
                        "price": 0.4083,
                        "step_size": 1
                    }
                ],
                "restrictions": {
                    "start_date": "2025-01-01",
                    "end_date": "2025-11-19"
                }
            }
        ],
        "last_updated": "2026-02-12T02:20:04Z"
    }
]
